name: Submodule Sync
on:
  repository_dispatch:
    types:
      - update-mindoo

jobs:
  submodule-sync:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive --remote
    - name: push
      uses: actions-x/commit@v2
      with:
        message: "Updated submodules"
